### ISSUE TITLE
日本語が文字化けする

### ISSUE THREAD

**Issue by vatscy** [InoueDaiki/mti-engineer-internship#1]
掲題の通りです。困っています。

**Comment by InoueDaiki** [comment]
chat.htmlではメッセージ内容をエスケープしてからサーバに送信していたのですが、サーバから取得した後に案エスケープしていませんでした。
ご確認お願い致します。

**Comment by vatscy** [comment]
chat.htmlの修正は問題なさそうです。
加えて、チャンネルの説明も文字化けしているようです。

**Comment by vatscy** [comment]
おっと、修正入りましたね。確認します。

**Comment by vatscy** [comment]
問題ないと思います！
