### ISSUE TITLE
【要望】チャット画面からチャンネル一覧画面に戻るリンクがほしい

### ISSUE THREAD

**Issue by vatscy** [InoueDaiki/mti-engineer-internship#3]
掲題の通りです。
あと欲を言うとログアウト（login.htmlに戻るだけ）も欲しいですが優先度は低めです。

**Comment by InoueDaiki** [comment]
@vatscy 
戻るボタンとログアウトボタンを設置しました。
ご確認お願い致します。

**Comment by vatscy** [comment]
完璧です。ありがとうございます。
