### ISSUE TITLE
コードレビュー

### ISSUE THREAD

**Issue by vatscy** [InoueDaiki/mti-engineer-internship#5]
コードは全体的によく書けていると思います。
バグは無いですが1点気になったので指摘しておきます。

JavaScriptはセミコロンが抜けても動いてしまうのですが、予期せぬバグを生まないために付与を徹底しておきたいところです。見逃しがちなのは、変数にオブジェクトや関数など複数行に渡るものを代入する以下のようなケース。実際数カ所抜けています。
```javascript
var data = {
  "uid": uid,
  "password": password
} // ←ここにセミコロン必要
```

**Comment by InoueDaiki** [comment]
@vatscy 
ご指摘ありがとうございます。
セミコロンに関しては修正しました。

**Comment by vatscy** [comment]
細かいですが `login.js` の3行目にもセミコロン必要です。

**Comment by vatscy** [comment]
あと追加ですみません。
エラー時にアラート出す際に、 `response.responseText` ではなく、そのJSON内の `message` の値を出すようにしてください。

**Comment by InoueDaiki** [comment]
@vatscy messageを出すようにしました

**Comment by vatscy** [comment]
ありがとうございます！
諸々問題なさそうなので、全てのブランチをmasterにマージしておいてください。
