### ISSUE TITLE
Lambdaの処理について

### ISSUE THREAD

**Issue by SeiyaMogami** [InoueDaiki/mti-engineer-internship#7]
Lambdaに書いてもらった処理があると思うのですが、インターン開始時に井上くんのLambdaを残しておくわけにはいきません。そこで、このリポジトリに新たにLambdaディレクトリを作って、Lambdaの処理内容をコピーしてJSファイルとして別途保存しておいてください。

お願いしまーす。

**Comment by InoueDaiki** [comment]
masterブランチに追加しました #10
